language: rust
rust:
  - stable
  - nightly
matrix:
  allow_failures:
    rust: 
      - nightly
before_script:
  - rustup component add rustfmt
script:
  - cargo fmt --all -- --check --verbose
  - cargo build --verbose --all
  - cargo test --verbose --all -- --test-threads=1
